name: 'Docs Compilation'

on:
  push:
    branches: ['main']

jobs:
  compile_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 22
      - run: npm ci
      - run: npm test
      - run: npm run build
