name: 'Docs Compilation'

on:
  push:
    branches: ['main']

jobs:
  compile_docs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt-get update
          ls -a
          # We can include document here if needed
          echo "Documentation compilation step executed."
          echo "Documentation compiled successfully."
